### PR TITLE
Recycler get item view type handling

### PR DESCRIPTION
**Pull request by gianlucaparadise**
Added GetItemViewTypeDelegate to decide the view type id depending on the position

### CODE REVIEW

**Comment by lbugnion** [comment]
Hi,

Thanks for your pull request. Can you explain the utility of the additional delegate? Maybe you have a sample?

Thanks
Laurent

**Comment by gianlucaparadise** [comment]
With this delegate you can build heterogenous layouts inside RecyclerView.
You can put logic inside `GetItemViewTypeDelegate` and return a different `int` for each layout type. Then you will receive this index as parameter in `CreateViewHolderDelegate` so you can create a different view holder for each view type.

Here you can read a tutorial about this: [Heterogenous Layouts inside RecyclerView](https://guides.codepath.com/android/Heterogenous-Layouts-inside-RecyclerView)

**Comment by lbugnion** [comment]
Hi, yes this sounds like a good idea. Merging here and will look to do a new official release with this feature.

**Comment by oleksandrmykhaylyshyn** [comment]
When is this planned to be released?

**Pull request merged**
