### PR TITLE
Fix for #41: Designtime Exception when mixing .NET Standard project libraries with WPF .NET Framework application

### PR DESCRIPTION
**Pull request by olitee**
Simple implementation of a fix for #41.

It might be worth adding additional try-catches around the other calls to GetType() - but this fix resolves the issue raised in #41.

### CODE REVIEW

**Comment by olitee** [comment]
@lbugnion I know try/catch/ignore is not a great pattern in general, but I think it's justified here, as it's a one-time static check of the environment for designtime purposes. The strategy in this class is 'Try this .. nope? OK, try this ... etc'

The original method assumes that, when attempting to load the `System.ComponentModel.DesignerProperties` assembly, it will either succeed or get null. However, in this new scenario we're actually getting a **mismatch** on the assembly version, which is throwing an exception.

**Comment by lbugnion** [comment]
Thanks for this. I will release a new version before end of 2018.

**Comment by olitee** [comment]
Thanks @lbugnion, I was hoping you'd merge this in. I was beginning to think I was the only one with this issue. :)

**Comment by lbugnion** [comment]
My tardiness is only a result of the new job keeping me busier than ever. Not any judgment on the issue itself 😉 I am looking to build a new CICD pipeline over the holidays to make building new Nuget packages easier.

Laurent Bugnion, Microsoft- +41 79 537 78 08
________________________________

**Comment by olitee** [comment]
I assume you're thinking of Azure DevOps? It's made our life so much easier since switching.

**Comment by lbugnion** [comment]
Yes exactly. I will work with some of my colleagues to build a nice pipeline.

Laurent Bugnion, Microsoft- +41 79 537 78 08
________________________________

**Comment by virzak** [comment]
Hello,

Is it possible to release this?

Otherwise we have to use
```csharp
DesignerProperties.GetIsInDesignMode(new System.Windows.DependencyObject())
```

**Pull request merged**
